add: Navigation Component
kavyakunder/Robocon-UI-CL pull request #11
Opened 2022-02-07 09:33 UTC by kavyakunder

Navigation Component consists of logo ,tabs and  icons.

![navigation1](https://user-images.githubusercontent.com/81958043/152761890-c81e0a43-3e5c-4441-be02-835acf89bb23.png)

2022-02-07 09:55 UTC, dev-enforced requested changes
The code and the output produced by it looks very good to me. Suggested some minor changes and then you can merge.Good work Kavya on the nav.

2022-02-07 09:55 UTC, dev-enforced commented on Components/Navigation/navigation.css
> +.navbar img {
Suggestion:
Instead of selecting the image element inside the navbar you can pass a class related to that img named as navbar-logo and then pass the styles as .navbar .navbar-logo{
//style properties
}

2022-02-07 09:55 UTC, dev-enforced commented on Components/Navigation/navigation.css
> +  text-decoration: none;
You can use this as a utility class in one of your style guide named as .link-not-decorated{text-decoration:none;} and pass it to that hyperlink because you might be using it frequently so few lines of code will get used frequently 
And avoid selecting the elements name the classes to which you want to apply the styles with appropriate names and then you can  pass it to that element where you want to apply within the HTML file.

2022-02-07 09:55 UTC, dev-enforced commented on Components/Navigation/navigation.html
> +              <img src="../../assets/brand-logo.png" alt="" />
Pass a value inside the alt attribute according to the image content.

2022-02-07 09:55 UTC, dev-enforced commented on Components/Navigation/navigation.css
> +.nav-items ul li a:hover {
Here also same as above.

2022-02-07 13:12 UTC, dev-enforced approved these changes

2022-02-10 17:00 UTC, Radheshyam1234 reviewed
looks good

2022-02-11 19:21 UTC, merged