add: Modal Component
kavyakunder/Robocon-UI-CL pull request #13
Opened 2022-02-07 13:31 UTC by kavyakunder

Modal Component pops up a message along with dismiss icon

https://user-images.githubusercontent.com/81958043/152797242-116b3ff1-5518-4ea2-a9df-33b1d01c932d.mp4

2022-02-07 13:37 UTC, GuptaEesh reviewed
Looks good to me

2022-02-08 16:20 UTC, dev-enforced requested changes
The code and output looks good to me . You can merge it.Had some small clarifications so asking it here:

2022-02-08 16:20 UTC, dev-enforced commented on Components/Modal/modal.css
> +.modal:target {
You can comment out what this selector does in general?

2022-02-08 16:20 UTC, dev-enforced commented on Components/Modal/modal.html
> +            alt="conquering responsive layouts"
This is a good Alt one!!Conquering Responsive Layouts made possible through Robocon UI

2022-02-08 16:20 UTC, dev-enforced commented on Components/Modal/modal.css
> +  padding: 1em 2em;
Instead of using rem em is used ?It is because of responsive nature of modal?

2022-02-08 16:20 UTC, dev-enforced commented on Components/Modal/modal.css
> +  font-size: 21px;
You can add this as a font-size variable in your CSS default file as --modal-link-fontsize:21px and use it here if using it frequently.

2022-02-09 17:16 UTC, kavyakunder commented on Components/Modal/modal.css
> +.modal:target {
It is used to highlight a specific content. So the link of the modal button is refers to modal container which displays a message. The better approach would be I guess to do in JS where  we could use onClick  and add the class which has opacity 1.

2022-02-09 17:17 UTC, kavyakunder commented on Components/Modal/modal.css
> +  padding: 1em 2em;
Changed it to rem to stay consistent with units.

2022-02-09 17:19 UTC, kavyakunder commented on Components/Modal/modal.css
> +  font-size: 21px;
Used it just once here. For frequently used other values like 1rem , I made the changes.

2022-02-09 17:27 UTC, dev-enforced approved these changes
You can merge it Kavya. Changes done!!

2022-02-09 17:32 UTC, merged